
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  WaistJoint_position_controller:
    type: effort_controllers/JointPositionController
    joint: WaistJoint
    pid: {p: 5000.0, i: 10, d: 0.0}
  ArmBaseJoint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ArmBaseJoint
    pid: {p: 5000.0, i: 10, d: 0.0}
  Arm12Joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm12Joint
    pid: {p: 5000.0, i: 10, d: 0.0}
  Arm23Joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm23Joint
    pid: {p: 5000.0, i: 10, d: 0.0}
